import { InfoResponse } from "@/constants/types";

const COINMARKETCAP_API_KEY = process.env.COINMARKETCAP_API_KEY!;

export async function GET(request: Request) {
  const url = new URL(request.url);

  const id = url.searchParams.get("id");
  try {
    // const response = await fetch(
    //   `https://pro-api.coinmarketcap.com/v2/cryptocurrency/info?id=${id}`,
    //   {
    //     headers: {
    //       "X-CMC_PRO_API_KEY": COINMARKETCAP_API_KEY,
    //     },
    //   }
    // );

    const res = result;

    return Response.json({
      result: res,
    });
  } catch (ex) {
    return Response.json({
      error: "Error when fetching the data",
    });
  }
}
const result: InfoResponse = {
  "1": {
    id: 1,
    name: "Bitcoin",
    symbol: "BTC",
    category: "coin",
    description:
      "Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,891,256. The last known price of Bitcoin is 117,906.9990064 USD and is down -0.02 over the last 24 hours. It is currently trading on 12253 active market(s) with $64,445,425,501.04 traded over the last 24 hours. More information can be found at https://bitcoin.org/.",
    slug: "bitcoin",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
    subreddit: "bitcoin",
    notice: "",
    tags: [
      "mineable",
      "pow",
      "sha-256",
      "store-of-value",
      "state-channel",
      "coinbase-ventures-portfolio",
      "three-arrows-capital-portfolio",
      "polychain-capital-portfolio",
      "binance-labs-portfolio",
      "blockchain-capital-portfolio",
      "boostvc-portfolio",
      "cms-holdings-portfolio",
      "dcg-portfolio",
      "dragonfly-capital-portfolio",
      "electric-capital-portfolio",
      "fabric-ventures-portfolio",
      "framework-ventures-portfolio",
      "galaxy-digital-portfolio",
      "huobi-capital-portfolio",
      "alameda-research-portfolio",
      "a16z-portfolio",
      "1confirmation-portfolio",
      "winklevoss-capital-portfolio",
      "usv-portfolio",
      "placeholder-ventures-portfolio",
      "pantera-capital-portfolio",
      "multicoin-capital-portfolio",
      "paradigm-portfolio",
      "bitcoin-ecosystem",
      "layer-1",
      "ftx-bankruptcy-estate",
      "2017-2018-alt-season",
      "us-strategic-crypto-reserve",
      "binance-ecosystem",
      "binance-listing",
    ],
    "tag-names": [
      "Mineable",
      "PoW",
      "SHA-256",
      "Store Of Value",
      "State Channel",
      "Coinbase Ventures Portfolio",
      "Three Arrows Capital Portfolio",
      "Polychain Capital Portfolio",
      "YZi Labs Portfolio",
      "Blockchain Capital Portfolio",
      "BoostVC Portfolio",
      "CMS Holdings Portfolio",
      "DCG Portfolio",
      "DragonFly Capital Portfolio",
      "Electric Capital Portfolio",
      "Fabric Ventures Portfolio",
      "Framework Ventures Portfolio",
      "Galaxy Digital Portfolio",
      "Huobi Capital Portfolio",
      "Alameda Research Portfolio",
      "a16z Portfolio",
      "1Confirmation Portfolio",
      "Winklevoss Capital Portfolio",
      "USV Portfolio",
      "Placeholder Ventures Portfolio",
      "Pantera Capital Portfolio",
      "Multicoin Capital Portfolio",
      "Paradigm Portfolio",
      "Bitcoin Ecosystem",
      "Layer 1",
      "FTX Bankruptcy Estate ",
      "2017/18 Alt season",
      "US Strategic Crypto Reserve",
      "Binance Ecosystem",
      "Binance Listing",
    ],
    "tag-groups": [
      "OTHERS",
      "ALGORITHM",
      "ALGORITHM",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "PLATFORM",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
    ],
    urls: {
      website: ["https://bitcoin.org/"],
      twitter: [],
      message_board: ["https://bitcointalk.org"],
      chat: [],
      facebook: [],
      explorer: [
        "https://blockchain.info/",
        "https://live.blockcypher.com/btc/",
        "https://blockchair.com/bitcoin",
        "https://explorer.viabtc.com/btc",
        "https://www.okx.com/web3/explorer/btc",
      ],
      reddit: ["https://reddit.com/r/bitcoin"],
      technical_doc: ["https://bitcoin.org/bitcoin.pdf"],
      source_code: ["https://github.com/bitcoin/bitcoin"],
      announcement: [],
    },
    platform: null,
    date_added: "2010-07-13T00:00:00.000Z",
    twitter_username: "",
    is_hidden: 0,
    date_launched: "2010-07-13T00:00:00.000Z",
    contract_address: [],
    self_reported_circulating_supply: null,
    self_reported_tags: null,
    self_reported_market_cap: null,
    infinite_supply: false,
  },
};
